### ISSUE TITLE
Discussion: is recording the offset usefull?

### ISSUE THREAD

**Issue by degski** [chmike/timez-go#1]
Hi Christophe,

I was working on/thinking about the same issue as this lib (and timez) addresses. Don't take this as criticism [I don't have a solution either, just some ideas], but I don't think [that's the conclusion I've come to at least] it is the right solution. What one needs, IMO, is together with the UTC-time, to record the IANA time-zone (or Windows-timezone). Unless you do that, it is not possible to convert back to local time under all conditions, i.e. iff you know UTC time and the time-zone it applies to, it should be possible to work out what the local time was/is in that timezone, taking into account (dynamic) DST. Offset cannot do this, due to DST (and possibly dynamic DST). 

I think you worked out nicely that 53-bits for time does the trick, this works well with Windows FILETIME as well, as most of those lower bits [FILETIME is in nanoseconds (since the year 1601), the timers in Windows don't have a resolution better than 400 to 600 ns] are practically speaking just garbage, in other words, it's possible to encode things in the lower bits, while just using the encoded FILETIME with the Win32-API, without any noticeable effect.

I'm thinking about encoding the time-zones (IANA 459/ Windows Native 159), so iff numbered, they can easily be inside the 11 bits available.

I don't know, what are your thoughts?

Have a nice day (et salutations),

degski

**Comment by chmike** [comment]
The solution you reach on the requirements you have. My requirements were to have store a time point which to determine the local time and the UTC time. The UTC time is to be used as global time reference for sorting. The encoding I came up with does that. UTC time comparison is obtained by the 64 bit unsigned integer. The local time, which includes the DST, is obtained by adding the offset. It's trivial and fast math operations. 

The *timez* time point is the binary equivalent of the ISO 8601 ASCII encoded time point. 

By storing the IANA time zone, you need a special computation and lookup to get the local time. This is the kind of things I wanted to avoid.

**Comment by degski** [comment]
Thanks for that, iff you only need local & UTC time, and only need this local time [sort of] instantly, that could suffice. It seems simpler to just store the **current local offset** in a global.

I think that also in your use-case, if you want to make this robust, you need to store the time-zone somehow and not the offset. I see your not liking computation and lookup [me no like either], but if you always want/need the correct answer, also in corner cases, you'll have to make those calculations, I'm afraid.

PS: if you set the offset in terms of the number of chunks of 15 minutes, 8 bits will do to store the offset. This then also gives you a simpler way to actually manipulate it as you now don't need to 'bit-fiddle', but you can just do a cast on the pointer and change it directly, something like this:

    using filtime_t = FILETIME;

    struct alignas ( 8 ) wintime_t {

        filtime_t * data ( ) noexcept { return &value; }
        filtime_t const * data ( ) const noexcept { return &value; }

        inline std::uint64_t & as_uint64 ( ) noexcept { return *reinterpret_cast<std::uint64_t *> ( this ); }
        inline std::uint64_t const & as_uint64 ( ) const noexcept { return *reinterpret_cast<std::uint64_t const *> ( this ); }

        void set_utc ( ) noexcept { *reinterpret_cast<char *> ( this ) = 0; }

        void set_offset ( int const minutes_ ) noexcept {
            assert ( not( minutes_ % 15 ) );
            *reinterpret_cast<char *> ( this ) = static_cast<char> ( minutes_ / 15 );
        }
        int get_offset ( ) const noexcept { return static_cast<int> ( *reinterpret_cast<char const *> ( this ) ) * 15; }

        private:
        filtime_t value{};
    };

**Comment by chmike** [comment]
The solution you reach depends on the requirements you have. My requirements were to store a time point which allows to determine the local time and the UTC time. The purpose of UTC time is to be used as global time reference for sorting. The encoding I came up with does that. UTC time comparison is obtained by the 64 bit unsigned integer. The local time, which includes the DST, is obtained by adding the offset to the UTC time. It's trivial and fast math operations. 

The time point we get with timez is equivalent to the ISO 8601 ASCII encoded time point. 

By storing the IANA time zone, you need a special computation and lookup to get the local time.

**Comment by chmike** [comment]
> It seems simpler to just store the current local offset in a global.

The purpose to store the time offset with the UTC time (not in a global) is to allow to determine the local time *where the time point was created*. Consider a messaging application for instance where users are in different time zone. With a single timez value you can determine the local time when the message was sent/received. You can also sort messages by UTC to get them in time sequence. Same for a web site with posts from users in different time zones. Storing the time offset in a global variable disallow that. 

The actual time encoding in mails includes time offset. The ISO 8601 ASCII time encoding also includes the time offset in addition to the UTC time. Timez is a binary version of the ISO 8601 time.

Timez is intended to be used as time stamps. That is the reason it is valid only since 1970. It can't encode time points before that.

I checked that the time offset range covers the current need. There shouldn't be any overflow or underflow in local time encoding.

**Comment by degski** [comment]
> Timez is intended to be used as time stamps.

I see the point now, you are always talking about current time (local or UTC), when making/creating that time-stamp. Thanks for elucidating all of that.
